language: csharp
mono: none
dist: xenial
dotnet:
 - 5.0
script:
 - dotnet restore
 - dotnet build
 - dotnet test Tests/Tests.csproj -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
after_success:
 - sudo apt-get update
 - sudo apt-get install apt-transport-https
 - sudo apt-get update
 - sudo apt-get install dotnet-sdk-2.1
 - dotnet tool install coveralls.net --version 1.0.0 --tool-path tools
 - export COVERALLS_REPO_TOKEN=nwDqYB8ldwuTdiZsmWRksx5aBNsxtZlIq
 - tools/csmacnz.Coveralls --opencover -i Tests/coverage.opencover.xml --useRelativePaths