matrix:
  include:
    - language: csharp
      mono: none
      dist: xenial
      dotnet: 3.1
      install:
        - dotnet restore
      script:
        - dotnet restore
        - dotnet build
        - cd Tests
        - dotnet test --collect:"XPlat Code Coverage"
        
    - language: csharp
      mono: none
      dist: xenial
      dotnet: 2.1
      script:
        - cd Tests
        - ls
