language: csharp
mono: none
dist: xenial
dotnet:
 - 3.1
install:
 - dotnet restore
 - dotnet add package coverlet.msbuild
script:
 - dotnet restore
 - dotnet build
 - cd Tests
 - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
after_success:
 - dotnet add package coveralls.net
 - csmacnz.Coveralls --opencover -i TestResults/*/coverage.cobertura.xml --useRelativePaths
