language: csharp
mono: none
dist: xenial
dotnet: 3.1
install:
  - dotnet restore
script:
 - dotnet restore
 - dotnet build
 - cd Tests
 - dotnet test --collect:"XPlat Code Coverage"
after_success:
 - pwd
 - reportgenerator "-reports:TestResults/*/coverage.cobertura.xml" "-targetdir:coveragereport" -reporttypes:Html
