language: csharp
mono: none
dist: xenial
dotnet: 3.1
install:
  - dotnet restore
script:
 - dotnet restore
 - dotnet build
 - cd Tests
 - dotnet test --collect:"XPlat Code Coverage"
after_success:
 - dotnet tool install -g coveralls.net --version 1.0.0 --tool-path tools
 - ./tools/csmacnz.Coveralls --opencover -i TestResults/*/coverage.cobertura.xml --useRelativePaths
